name: CI
on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

jobs:
  test:
    permissions: {}
    runs-on: ubuntu-latest
    env:
      inputs: ${{ toJSON(inputs) }}
      gh: ${{ toJSON(github) }}
    steps:
      - name: Run a multi-line script
        run: |
          (
            echo '# Report'
            echo "Date: $(date)"
            echo "Random: $RANDOM"
            echo "github: $gh"
            echo "inputs: $inputs"
          ) >> $GITHUB_STEP_SUMMARY
