name: CI
on:
  push:
  pull_request:

jobs:
  test:
    permissions: {}
    runs-on: ubuntu-latest
    env:
      inputs: ${{ toJSON(inputs) }}
      gh: ${{ toJSON(github) }}
    steps:
      - name: Run a multi-line script
        run: |
          to_json() {
            echo "## $1"
            echo '```json'
            echo "$2" | tr '\n' ' '
            echo
            echo '```'
            echo
          }
          (
            echo '# Report'
            echo "Date: $(date)"
            echo "Random: $RANDOM"
            to_json GitHub "$gh"
            to_json inputs "$inputs"
          ) >> $GITHUB_STEP_SUMMARY
